using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using JetBrains.Annotations;
using System.IO;
using Unity.VisualScripting;

public class InventorySystem : MonoBehaviour
{
    public List<GameObject> items = new List<GameObject>();
    public Dictionary<string, string> descriptions = new Dictionary<string, string>();
    public Dictionary<string, string> combinableItems = new Dictionary<string, string>();
    //public Dictionary<string, string> imageSprites = new Dictionary<string, string>();
    //private int itemNum = 1;

    private void Start()
    {
        //combinableItems.Add("TestItem1", "TestItem3");
        //combinableItems.Add("TestItem3", "TestItem1");
        //combinableItems.Add("Blackbox", "Notes");
        //combinableItems.Add("Notes", "Blackbox");
        //combinableItems.Add("TestItem2", " ");
        //combinableItems.Add("Satellite", " ");
        //combinableItems.Add("TestItem4", " ");

        // --- First area combinable items ---
        combinableItems.Add("ASU Trinket", " ");
        combinableItems.Add("Electromagnetic Fields", "Solar Panels");
        combinableItems.Add("Solar Panels", "Electromagnetic Fields");
        combinableItems.Add("Falcon Heavy Launcher", " ");
        combinableItems.Add("Xenon Rocket Engines", " ");

        // --- Second area combinable items ---
        combinableItems.Add("Neutron Spectrometer", "Cosmic Rays");
        combinableItems.Add("Cosmic Rays", "Neutron Spectrometer");   
        combinableItems.Add("Magnetometer", " ");
        combinableItems.Add("X-Band Radio Frequency", " ");
        combinableItems.Add("Gamma Ray Spectrometer", " ");


        // First area item descriptions
        descriptions.Add("ASU Trinket", "A trinket of a university in Arizona that is leading the development and" +
            " launch of the Psyche space mission and well known for other scientific initiatives.");

        descriptions.Add("Solar Panels", "Solar panels generate electricity by using electrons generated by sunlight" +
            " and are used on many spacecraft for its reliability and renewability.");

        descriptions.Add("Electromagnetic Fields", "A field of moving electrons that has many applications, one being" +
            " the generation of charged atoms. If there was a way to power an electromagnetic field it would be an extremely" +
            " efficient form of movement in a vacuum.");

        descriptions.Add("Falcon Heavy Launcher", "A lower rocket stage to reach low to high orbit developed by SpaceX that is" +
            " used in some modern day space missions for its reliability and power");

        descriptions.Add("Xenon Rocket Engines", "An extremely efficient engine design that uses charged atoms from electromagnetic" +
            " fields to thrust forwards. This creates a small amount of thrust in a vacuum but uses extremely little energy and fuel" +
            " to do so and is used on both the Psyche probe and many other long distance missions.");

        // Second area item descriptions
        descriptions.Add("Magnetometer", "A device that measures magnetic fields created by both magnetic metals and " +
            "planetary objects such as earth");

        descriptions.Add("Cosmic Rays", "Charged particles that are from stars such as the sun and when the particles hit" +
            " a surface that surface emits a specific amount and type of neutrons and gamma rays");

        descriptions.Add("X-Band Radio Frequency", "A specific range of radio waves that are used for radar imaging to better" +
            " visualize an area");

        descriptions.Add("Neutron Spectrometer", "A device that measures the amount of neutrons being released from a material" +
            " or area that can be used to identify what a specific material might be made of");

        descriptions.Add("Gamma Ray Spectrometer", "This device measures the amount and type of gamma rays a material emits when" +
            " hit by cosmic rays, the amount and type are unique for each element and is extremely useful for determining what an" +
            " asteroid or planet is made of");


    }

    public bool findItem(string searchedName)
    {
        foreach (GameObject item in items)
        {
            if (item.name == searchedName)
            {
                return true;
            }
                
        }
        return false;
    }

    public void AddItem(GameObject item)
    {
        items.Add(item);
        //descriptions.Add(item.name, "Test Description #" + itemNum);
        //itemNum++;
    }
}
